spring.main.web-application-type=servlet
spring.config.import=optional:file:.env[.properties]
spring.profiles.active=prod
server.port=8080
spring.web.resources.static-locations=file:/app/static/,file:/app/src/main/resources/static/,classpath:/static/
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.datasource.url=${DATABASE_URL}
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql
